pipeline:
  name: maven-cicd-demo
  identifier: mavencicddemo
  projectIdentifier: labs_sudha
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.github_sudha
        repoName: maven_projects
        build: <+input>
  stages:
    - stage:
        name: Build App
        identifier: Build_App
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-22
          execution:
            steps:
              - step:
                  type: Run
                  name: Build App
                  identifier: Build_App
                  spec:
                    connectorRef: account.docker
                    image: maven:3.6.3-jdk-11
                    shell: Bash
                    command: |-
                      cd maven-cicd-demo

                      mvn -B clean test package
              - step:
                  name: Build Docker Image
                  identifier: Docker_Build
                  type: Run
                  spec:
                    shell: Bash
                    command: |-
                      export IMAGE="${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}"
                      cd maven-cicd-demo
                      docker build -t $IMAGE .
                      docker image ls

                      TOKEN="<+secrets.getValue(\"account.docker_ro_pat\")>"
                      echo "TOKEN LENGTH: ${#TOKEN}"
                      printf '%q\n' "$TOKEN"
                      echo "$TOKEN" | docker login -u "sudha098" --password-stdin

                      docker push $IMAGE
                    envVariables:
                      DOCKER_REGISTRY: index.docker.io
                      IMAGE_NAME: sudha098/maven-cicd-demo
                      TAG: <+pipeline.executionId>
              - step:
                  name: Save Artifact Info
                  identifier: Save_Artifact
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "image=${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}" > artifact.properties
                      cat artifact.properties
                    envVariables:
                      DOCKER_REGISTRY: index.docker.io
                      IMAGE_NAME: sudha098/maven-cicd-demo
                      TAG: <+pipeline.executionId>
    - stage:
        name: Deploy to Dev
        identifier: Deploy_to_Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: Deploy_to_Dev
      type: String
      description: ""
      required: true
      value: <+input>.default(false).selectOneFrom(true,false)
